***Exp-2: PROGRAM TO CREATE A MULTI-LAYER NEURAL NETWORK***

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt    

In [ ]:
# Read Data
from google.colab import files
files.upload()

Saving Mobile_Price_Classification_train.csv to Mobile_Price_Classification_train.csv


{'Mobile_Price_Classification_train.csv': b'battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range\n842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1,1\n1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0,2\n563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0,2\n615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0,2\n1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0,1\n1859,0,0.5,1,3,0,22,0.7,164,1,7,1004,1654,1067,17,1,10,1,0,0,1\n1821,0,1.7,0,4,1,10,0.8,139,8,10,381,1018,3220,13,8,18,1,0,1,3\n1954,0,0.5,1,0,0,24,0.8,187,4,0,512,1149,700,16,3,5,1,1,1,0\n1445,1,0.5,0,0,0,53,0.7,174,7,14,386,836,1099,17,1,20,1,0,0,0\n509,1,0.6,1,2,1,9,0.1,93,5,15,1137,1224,513,19,10,12,1,0,0,0\n769,1,2.9,1,0,0,9,0.1,182,5,1,248,874,3946,5,2,7,0,0,0,3\n1520,1,2.2,0,5,1,33,0.5,177,8,18,151,1005,3826,14,9,13,1,1,1,3\n1815,0,2.8,0,2,0,33,0.6,159,4,17,607,748

In [ ]:
df = pd.read_csv('Mobile_Price_Classification_train.csv')
print(df)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

Understand your data

In [ ]:
df.shape

(2000, 21)

Separate the attributes and the class label

In [ ]:
data=df.drop(['price_range'],axis=1)
label=df['price_range']
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7   
1       0.7        136        3   6        905      1988  2631    17     3   
2       0.9        145        5   6       1263      1716  2603    11     2   
3       0.8        131        6   9       1216      1786  2769    16     8   
4       0.6        141        2  14       1208      1212  1411     8     2   
...     ...        ...      ...  ..        ...       ...   ...   ...   ...   
1995    0.8        106        6  14       1222      1890   668    13     4   
1996    0.2        187        4   3        915      1965  2032    11    10   
1997    0.7        108        8   3        868      1632  3057     9     1   
1998    0.1        145        5   5        336       670   869    18    10   
1999    0.9        168        6  16        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  
0            19        0             0     1  
1             7        1             1     0  
2             9        1             1     0  
3            11        1             0     0  
4            15        1             1     0  
...         ...      ...           ...   ...  
1995         19        1             1     0  
1996         16        1             1     1  
1997          5        1             1     0  
1998         19        1             1     1  
1999          2        1             1     1  

[2000 rows x 20 columns]

In [ ]:
label

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

Data preprocessiong- Standardize the attributes

In [ ]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(data)
scaler
scaler.mean_

array([1.2385185e+03, 4.9500000e-01, 1.5222500e+00, 5.0950000e-01,
       4.3095000e+00, 5.2150000e-01, 3.2046500e+01, 5.0175000e-01,
       1.4024900e+02, 4.5205000e+00, 9.9165000e+00, 6.4510800e+02,
       1.2515155e+03, 2.1242130e+03, 1.2306500e+01, 5.7670000e+00,
       1.1011000e+01, 7.6150000e-01, 5.0300000e-01, 5.0700000e-01])

In [ ]:
print(scaler)

StandardScaler()


Perform standardization by centering and scaling

In [ ]:
df_scaled = scaler.transform(data)
df_scaled

array([[-0.90259726, -0.9900495 ,  0.83077942, ..., -1.78686097,
        -1.00601811,  0.98609664],
       [-0.49513857,  1.0100505 , -1.2530642 , ...,  0.55964063,
         0.99401789, -1.01409939],
       [-1.5376865 ,  1.0100505 , -1.2530642 , ...,  0.55964063,
         0.99401789, -1.01409939],
       ...,
       [ 1.53077336, -0.9900495 , -0.76274805, ...,  0.55964063,
         0.99401789, -1.01409939],
       [ 0.62252745, -0.9900495 , -0.76274805, ...,  0.55964063,
         0.99401789,  0.98609664],
       [-1.65833069,  1.0100505 ,  0.58562134, ...,  0.55964063,
         0.99401789,  0.98609664]])

Mean=0 and SD=1 for standardized dataset

In [ ]:
df_scaled.mean(axis=0)

array([ 2.14939178e-16, -1.24344979e-17, -1.54543045e-16,  8.08242362e-17,
        5.86197757e-17,  1.04805054e-16, -9.59232693e-17, -1.03028697e-16,
        1.27897692e-16, -7.72715225e-17,  1.40332190e-16,  1.18127730e-16,
        6.08402217e-17, -1.81188398e-16,  4.88498131e-17, -5.50670620e-17,
        1.42108547e-16,  1.42108547e-17, -5.41788836e-17,  1.42108547e-17])

In [ ]:
df_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

Convert Numpy array to dataframe

In [ ]:
dataframe=pd.DataFrame(df_scaled,columns=['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g', 
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'])

In [ ]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

Train-Test split

In [ ]:
from sklearn.model_selection import train_test_split
datasets = train_test_split(dataframe, 
                            label,
                            test_size=0.2)

train_data, test_data, train_labels, test_labels = datasets

In [ ]:
train_data.shape

(1600, 20)

In [ ]:
test_data.shape

(400, 20)

MLP Classifier

In [ ]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(solver='adam', 
                    alpha=1e-5,
                    hidden_layer_sizes=(17,12,7), 
                    random_state=1,max_iter=900)

clf.fit(train_data,train_labels)     

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(17, 12, 7), max_iter=900,
              random_state=1)

In [ ]:
clf.score(train_data, train_labels)

1.0

Print accuracy score for training set

In [ ]:
from sklearn.metrics import accuracy_score
predictions_train = clf.predict(train_data)
train_score = accuracy_score(predictions_train,train_labels)
print("score on train data: ", train_score)

score on train data:  1.0


Perform classification for test set and print the accuracy score

In [ ]:
predictions_test = clf.predict(test_data)
predictions_test

array([1, 2, 3, 3, 1, 3, 1, 3, 3, 0, 3, 0, 0, 1, 0, 2, 3, 0, 1, 2, 2, 3,
       2, 0, 2, 3, 2, 3, 1, 1, 1, 1, 1, 2, 3, 1, 0, 2, 0, 2, 2, 2, 2, 2,
       0, 2, 3, 3, 3, 3, 3, 2, 2, 2, 1, 3, 0, 3, 3, 3, 1, 1, 0, 2, 3, 2,
       3, 2, 0, 0, 1, 3, 3, 2, 3, 2, 1, 2, 2, 0, 1, 3, 3, 0, 0, 1, 0, 2,
       2, 0, 0, 3, 0, 1, 0, 0, 2, 1, 2, 3, 0, 1, 1, 0, 2, 1, 0, 3, 0, 2,
       3, 2, 2, 1, 2, 1, 0, 3, 1, 3, 0, 3, 3, 3, 2, 1, 1, 3, 1, 3, 2, 1,
       1, 3, 2, 3, 1, 0, 3, 1, 1, 3, 0, 0, 3, 2, 1, 0, 2, 2, 0, 1, 0, 3,
       0, 2, 2, 3, 3, 1, 0, 2, 0, 1, 3, 0, 2, 1, 1, 1, 3, 2, 0, 1, 2, 0,
       3, 3, 3, 1, 1, 1, 2, 0, 0, 1, 2, 2, 1, 2, 3, 1, 0, 2, 2, 1, 2, 0,
       2, 1, 0, 3, 2, 0, 2, 0, 2, 3, 1, 1, 0, 2, 0, 1, 2, 3, 1, 2, 0, 2,
       2, 2, 0, 0, 0, 0, 0, 1, 0, 3, 1, 1, 0, 3, 0, 1, 1, 3, 0, 1, 3, 1,
       0, 2, 3, 3, 3, 2, 3, 0, 2, 2, 0, 2, 0, 2, 3, 1, 0, 3, 1, 3, 0, 2,
       1, 3, 1, 1, 2, 0, 1, 2, 3, 1, 3, 0, 2, 2, 0, 0, 3, 2, 3, 0, 2, 0,
       2, 0, 0, 1, 2, 2, 0, 3, 3, 2, 0, 3, 0, 1, 0,

In [ ]:
test_labels

1900    1
1478    2
1206    3
1497    3
1358    1
       ..
1329    1
1660    1
167     2
138     0
747     1
Name: price_range, Length: 400, dtype: int64

In [ ]:
test_score = accuracy_score(predictions_test, test_labels)
print("score on test data: ", test_score)

score on test data:  0.93


Print weights

In [ ]:
print("weights between input and first hidden layer:")
print(clf.coefs_[0])
print("\nweights between first hidden and second hidden layer:")
print(clf.coefs_[1])
print("\nweights between second hidden and third hidden layer:")
print(clf.coefs_[2])
print("\nweights between third hidden layer and output layer:")
print(clf.coefs_[3])

weights between input and first hidden layer:
[[ 3.71171605e-01  5.15045725e-02 -5.87550782e-01  1.20489717e-01
   1.32683747e-01 -3.20046679e-02  2.48151356e-01  1.97299185e-01
   1.48362126e-01  2.47932934e-01  2.58823894e-01  2.73918279e-01
  -3.28708053e-01  3.76536176e-01 -6.33597346e-01 -2.52338108e-01
  -3.42951558e-01]
 [ 2.64630889e-01 -2.08165016e-01  2.56862460e-01  1.72784060e-01
   2.09371066e-02  6.33906448e-02  2.17073342e-01  9.77717775e-02
  -2.01649572e-02 -5.49792576e-01 -4.34154397e-01 -8.80039170e-02
   5.83745581e-02 -6.65402948e-01 -2.98765995e-03  1.64554538e-02
   1.28028545e-01]
 [ 1.89564776e-02 -3.63895337e-02 -4.73202264e-03  1.46075934e-01
  -3.13135932e-01  1.29106972e-01  1.59679837e-01  8.47393290e-02
   2.84466325e-02  3.74934056e-01 -2.22795868e-01  4.45299324e-02
   3.06910934e-01 -1.54245207e-01 -2.12619376e-01  3.60741607e-02
  -2.22722519e-01]
 [-3.43171289e-02 -2.74537995e-02  1.47688557e-01  1.03591807e-01
  -1.82195805e-01  2.09732936e-01 -4.02

Print the weight between the layers

In [ ]:
for i in range(len(clf.coefs_)):
    number_neurons_in_layer = clf.coefs_[i].shape[1]
    for j in range(number_neurons_in_layer):
        weights = clf.coefs_[i][:,j]
        print(i, j, weights, end=", ")
        print()
    print()

0 0 [ 0.3711716   0.26463089  0.01895648 -0.03431713  0.19579292  0.29136674
  0.24674913  0.14168768  0.25307926 -0.10963826  0.13909432  0.240042
 -0.13967044  0.13272174 -0.23444303  0.20445762 -0.30936872 -0.02487403
 -0.01027423 -0.18780805], 
0 1 [ 0.05150457 -0.20816502 -0.03638953 -0.0274538  -0.22585768  0.09524356
  0.04041213 -0.11001383 -0.1214111  -0.19645237  0.45240499 -0.19119507
  0.00313148 -0.65199244 -0.00096564  0.10732248 -0.09722869  0.09168732
 -0.11526435  0.26048985], 
0 2 [-0.58755078  0.25686246 -0.00473202  0.14768856  0.1772806   0.36080862
  0.3186503  -0.19386537  0.20376344 -0.10213384 -0.05559378 -0.04935989
 -0.06694016 -0.14490555  0.05526434 -0.19277834  0.49508926  0.21612867
 -0.08202914  0.2458324 ], 
0 3 [ 0.12048972  0.17278406  0.14607593  0.10359181 -0.27253202 -0.12572131
  0.23458782 -0.48293106  0.26992681 -0.10956827  0.06101896 -0.09879866
  0.20495994 -0.1626998   0.56180938 -0.13592178  0.06697572 -0.11167912
 -0.28542108 -0.47404015],

Print the bias 

In [ ]:
print("Bias values for first hidden layer:")
print(clf.intercepts_[0])
print("\nBias values for second hidden layer:")
print(clf.intercepts_[1])
print("\nBias values for third hidden layer:")
print(clf.intercepts_[2])
print("\nBias values for output hidden layer:")
print(clf.intercepts_[3])

Bias values for first hidden layer:
[ 1.15409291  0.57397122  1.02248283  0.94603796  0.19373682  0.72006978
  0.62075382  0.09269942  0.96280626  0.01012868 -0.01698106  0.87571111
  0.40452764  0.31079635  0.32044392  0.55374673  0.81397483]

Bias values for second hidden layer:
[ 6.65211550e-01  7.08308735e-01 -2.90456271e-01  1.07408742e-01
  3.82533053e-02  3.47205338e-01  6.34490998e-01 -2.30328313e-01
 -2.79702855e-03  4.20126897e-01  1.09574645e+00 -2.35917065e-04]

Bias values for third hidden layer:
[ 0.05576159  0.55381794 -0.51710743  0.00614649 -0.09304351 -0.09360683
 -0.34456269]

Bias values for output hidden layer:
[ 0.70921944  0.01618059 -0.59902353 -0.82030619]


Confusion matrix for train data

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(predictions_train, train_labels)

array([[390,   0,   0,   0],
       [  0, 402,   0,   0],
       [  0,   0, 400,   0],
       [  0,   0,   0, 408]])

Confusion matrix for test data

In [ ]:
confusion_matrix(predictions_test, test_labels)

array([[102,   2,   0,   0],
       [  8,  91,   4,   0],
       [  0,   5,  93,   6],
       [  0,   0,   3,  86]])

Classification report

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(predictions_test, test_labels))

              precision    recall  f1-score   support

           0       0.93      0.98      0.95       104
           1       0.93      0.88      0.91       103
           2       0.93      0.89      0.91       104
           3       0.93      0.97      0.95        89

    accuracy                           0.93       400
   macro avg       0.93      0.93      0.93       400
weighted avg       0.93      0.93      0.93       400

